### ISSUE TITLE
EventingBasicConsumer support

### ISSUE THREAD

**Issue by troutkilroy** [KyleCrowley/RabbitMQ.Fakes#17]
Maybe this is a bug, but in my tests binding an EventingBasicConsumer to a FakeChannel doesn't seem to receive messages.

rmqConsumer = new EventingBasicConsumer(rmqChannel);
        rmqConsumer.Received += (model, ea) => 
  {
  // message received...
  };
  rmqChannel.QueueDeclare(queueName, false, false);
  rmqChannel.BasicConsume(queueName, true, rmqConsumer);
  
  In the test examples I don't see that you have an example using EventingBasicConsumer. Is it supported?

**Comment by KyleCrowley** [comment]
Yes `EventingBasicConsumer` is supported (as well as `AsyncEventingBasicConsumer`) and there are a few tests that use it, such as [this one](https://github.com/KyleCrowley/RabbitMQ.Fakes.DotNetStandard/blob/main/RabbitMQ.Fakes.DotNetCore.Tests/FakeModelTests.cs#L915-L938).

The consumer will only receive messages in these cases:
1. A message was delivered to a queue (via an exchange) *before* the consumer started consuming from the queue. These messages will be delivered to the consumer immediately after consumption (via `BasicConsume`).
2. A message was delivered to a queue (via an exchange) *after* the consumer started consuming from the queue. These messages will be delivered to the consumer after the queue has received them.

I'm assuming you haven't delivered a message to an exchange (via `BasicPublish`), so the message is never delivered to your queue, and therefore, is never delivered to your consumer.

If you check the test case I listed, a message is being delivered to the default exchange, which is a special (direct) exchange in RabbitMQ that is automatically bound to all queues with a binding key of the queue name. You can use this exchange to deliver messages to your queue, or you can setup an exchange and bind your queue to it (there are plenty of examples in the tests).
